### ISSUE TITLE
Swiftwave management dashboard with `quickconnect` support

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave-dashboard#1]
**Tasks**
- [x] Quickconnect feature https://dashboard.swiftwave.org . user can provide IP of server and that's all. Without installing he can access dashboard #3 
- [x] Login Page & Authentication setup [cookie based] #3 
- [x] Create a service worker / background process to verify session validity each minute 
- [x] Volume Management #8
- [x] Domain Management #6 
- [x] Git credential Management #7
- [x] Application Management #11
- [x] Routing Management
  - [x] Ingress Rules #9
  - [x] Redirect Rules #3

**Comment by tanmoysrt** [comment]
All the requirrement has been completed :fire:
